<?php
/**
 * Static list of ISO 3166 region and country codes that will
 * be stored in database on activation
 *
 * @link       https://github.com/garretthunter
 * @since      1.1.0
 *
 * @package    Thematic_Maps
 * @subpackage Thematic_Maps/includes
 */

$iso_regions = array (
	"('', 'Afghanistan', 'AF', 'Asia', '142', 'Southern Asia', '034', TRUE),\n",
	"('', 'Åland Islands', 'AX', 'Europe', '150', 'Northern Europe', '154', TRUE),\n",
	"('', 'Albania', 'AL', 'Europe', '150', 'Southern Europe', '039', TRUE),\n",
	"('', 'Algeria', 'DZ', 'Africa', '002', 'Northern Africa', '015', TRUE),\n",
	"('', 'American Samoa', 'AS', 'Oceania', '009', 'Polynesia', '061', TRUE),\n",
	"('', 'Andorra', 'AD', 'Europe', '150', 'Southern Europe', '039', TRUE),\n",
	"('', 'Angola', 'AO', 'Africa', '002', 'Middle Africa', '017', TRUE),\n",
	"('', 'Anguilla', 'AI', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Antarctica', 'AQ', '', '', '', '', FALSE),\n",
	"('', 'Antigua and Barbuda', 'AG', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Argentina', 'AR', 'Americas', '019', 'South America', '005', TRUE),\n",
	"('', 'Armenia', 'AM', 'Asia', '142', 'Western Asia', '145', TRUE),\n",
	"('', 'Aruba', 'AW', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Australia', 'AU', 'Oceania', '009', 'Australia and New Zealand', '053', TRUE),\n",
	"('', 'Austria', 'AT', 'Europe', '150', 'Western Europe', '155', TRUE),\n",
	"('', 'Azerbaijan', 'AZ', 'Asia', '142', 'Western Asia', '145', TRUE),\n",
	"('', 'Bahamas', 'BS', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Bahrain', 'BH', 'Asia', '142', 'Western Asia', '145', TRUE),\n",
	"('', 'Bangladesh', 'BD', 'Asia', '142', 'Southern Asia', '034', TRUE),\n",
	"('', 'Barbados', 'BB', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Belarus', 'BY', 'Europe', '150', 'Eastern Europe', '151', TRUE),\n",
	"('', 'Belgium', 'BE', 'Europe', '150', 'Western Europe', '155', TRUE),\n",
	"('', 'Belize', 'BZ', 'Americas', '019', 'Central America', '013', TRUE),\n",
	"('', 'Benin', 'BJ', 'Africa', '002', 'Western Africa', '011', TRUE),\n",
	"('', 'Bermuda', 'BM', 'Americas', '019', 'Northern America', '021', TRUE),\n",
	"('', 'Bhutan', 'BT', 'Asia', '142', 'Southern Asia', '034', TRUE),\n",
	"('', 'Bolivia (Plurinational State of)', 'BO', 'Americas', '019', 'South America', '005', TRUE),\n",
	"('', 'Bonaire, Sint Eustatius and Saba', 'BQ', 'Americas', '019', 'Caribbean', '029', FALSE),\n",
	"('', 'Bosnia and Herzegovina', 'BA', 'Europe', '150', 'Southern Europe', '039', TRUE),\n",
	"('', 'Botswana', 'BW', 'Africa', '002', 'Southern Africa', '018', TRUE),\n",
	"('', 'Bouvet Island', 'BV', '', '', '', '', FALSE),\n",
	"('', 'Brazil', 'BR', 'Americas', '019', 'South America', '005', TRUE),\n",
	"('', 'British Indian Ocean Territory', 'IO', '', '', '', '', FALSE),\n",
	"('', 'Brunei Darussalam', 'BN', 'Asia', '142', 'South-Eastern Asia', '035', TRUE),\n",
	"('', 'Bulgaria', 'BG', 'Europe', '150', 'Eastern Europe', '151', TRUE),\n",
	"('', 'Burkina Faso', 'BF', 'Africa', '002', 'Western Africa', '011', TRUE),\n",
	"('', 'Burundi', 'BI', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'Cambodia', 'KH', 'Asia', '142', 'South-Eastern Asia', '035', TRUE),\n",
	"('', 'Cameroon', 'CM', 'Africa', '002', 'Middle Africa', '017', TRUE),\n",
	"('', 'Canada', 'CA', 'Americas', '019', 'Northern America', '021', TRUE),\n",
	"('', 'Cabo Verde', 'CV', 'Africa', '002', 'Western Africa', '011', TRUE),\n",
	"('', 'Cayman Islands', 'KY', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Central African Republic', 'CF', 'Africa', '002', 'Middle Africa', '017', TRUE),\n",
	"('', 'Chad', 'TD', 'Africa', '002', 'Middle Africa', '017', TRUE),\n",
	"('', 'Chile', 'CL', 'Americas', '019', 'South America', '005', TRUE),\n",
	"('', 'China', 'CN', 'Asia', '142', 'Eastern Asia', '030', TRUE),\n",
	"('', 'Christmas Island', 'CX', '', '', '', '', FALSE),\n",
	"('', 'Cocos (Keeling) Islands', 'CC', '', '', '', '', FALSE),\n",
	"('', 'Colombia', 'CO', 'Americas', '019', 'South America', '005', TRUE),\n",
	"('', 'Comoros', 'KM', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'Congo', 'CG', 'Africa', '002', 'Middle Africa', '017', TRUE),\n",
	"('', 'Congo (Democratic Republic of the)', 'CD', 'Africa', '002', 'Middle Africa', '017', TRUE),\n",
	"('', 'Cook Islands', 'CK', 'Oceania', '009', 'Polynesia', '061', TRUE),\n",
	"('', 'Costa Rica', 'CR', 'Americas', '019', 'Central America', '013', TRUE),\n",
	"('', 'Côte d\'Ivoire', 'CI', 'Africa', '002', 'Western Africa', '011', TRUE),\n",
	"('', 'Croatia', 'HR', 'Europe', '150', 'Southern Europe', '039', TRUE),\n",
	"('', 'Cuba', 'CU', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Curaçao', 'CW', 'Americas', '019', 'Caribbean', '029', FALSE),\n",
	"('', 'Cyprus', 'CY', 'Asia', '142', 'Western Asia', '145', TRUE),\n",
	"('', 'Czech Republic', 'CZ', 'Europe', '150', 'Eastern Europe', '151', TRUE),\n",
	"('', 'Denmark', 'DK', 'Europe', '150', 'Northern Europe', '154', TRUE),\n",
	"('', 'Djibouti', 'DJ', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'Dominica', 'DM', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Dominican Republic', 'DO', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Ecuador', 'EC', 'Americas', '019', 'South America', '005', TRUE),\n",
	"('', 'Egypt', 'EG', 'Africa', '002', 'Northern Africa', '015', TRUE),\n",
	"('', 'El Salvador', 'SV', 'Americas', '019', 'Central America', '013', TRUE),\n",
	"('', 'Equatorial Guinea', 'GQ', 'Africa', '002', 'Middle Africa', '017', TRUE),\n",
	"('', 'Eritrea', 'ER', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'Estonia', 'EE', 'Europe', '150', 'Northern Europe', '154', TRUE),\n",
	"('', 'Ethiopia', 'ET', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'Falkland Islands (Malvinas)', 'FK', 'Americas', '019', 'South America', '005', TRUE),\n",
	"('', 'Faroe Islands', 'FO', 'Europe', '150', 'Northern Europe', '154', TRUE),\n",
	"('', 'Fiji', 'FJ', 'Oceania', '009', 'Melanesia', '054', TRUE),\n",
	"('', 'Finland', 'FI', 'Europe', '150', 'Northern Europe', '154', TRUE),\n",
	"('', 'France', 'FR', 'Europe', '150', 'Western Europe', '155', TRUE),\n",
	"('', 'French Guiana', 'GF', 'Americas', '019', 'South America', '005', TRUE),\n",
	"('', 'French Polynesia', 'PF', 'Oceania', '009', 'Polynesia', '061', TRUE),\n",
	"('', 'French Southern Territories', 'TF', '', '', '', '', FALSE),\n",
	"('', 'Gabon', 'GA', 'Africa', '002', 'Middle Africa', '017', TRUE),\n",
	"('', 'Gambia', 'GM', 'Africa', '002', 'Western Africa', '011', TRUE),\n",
	"('', 'Georgia', 'GE', 'Asia', '142', 'Western Asia', '145', TRUE),\n",
	"('', 'Germany', 'DE', 'Europe', '150', 'Western Europe', '155', TRUE),\n",
	"('', 'Ghana', 'GH', 'Africa', '002', 'Western Africa', '011', TRUE),\n",
	"('', 'Gibraltar', 'GI', 'Europe', '150', 'Southern Europe', '039', TRUE),\n",
	"('', 'Greece', 'GR', 'Europe', '150', 'Southern Europe', '039', TRUE),\n",
	"('', 'Greenland', 'GL', 'Americas', '019', 'Northern America', '021', TRUE),\n",
	"('', 'Grenada', 'GD', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Guadeloupe', 'GP', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Guam', 'GU', 'Oceania', '009', 'Micronesia', '057', TRUE),\n",
	"('', 'Guatemala', 'GT', 'Americas', '019', 'Central America', '013', TRUE),\n",
	"('', 'Guernsey', 'GG', 'Europe', '150', 'Northern Europe', '154', TRUE),\n",
	"('', 'Guinea', 'GN', 'Africa', '002', 'Western Africa', '011', TRUE),\n",
	"('', 'Guinea-Bissau', 'GW', 'Africa', '002', 'Western Africa', '011', TRUE),\n",
	"('', 'Guyana', 'GY', 'Americas', '019', 'South America', '005', TRUE),\n",
	"('', 'Haiti', 'HT', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Heard Island and McDonald Islands', 'HM', '', '', '', '', FALSE),\n",
	"('', 'Holy See', 'VA', 'Europe', '150', 'Southern Europe', '039', TRUE),\n",
	"('', 'Honduras', 'HN', 'Americas', '019', 'Central America', '013', TRUE),\n",
	"('', 'Hong Kong', 'HK', 'Asia', '142', 'Eastern Asia', '030', TRUE),\n",
	"('', 'Hungary', 'HU', 'Europe', '150', 'Eastern Europe', '151', TRUE),\n",
	"('', 'Iceland', 'IS', 'Europe', '150', 'Northern Europe', '154', TRUE),\n",
	"('', 'India', 'IN', 'Asia', '142', 'Southern Asia', '034', TRUE),\n",
	"('', 'Indonesia', 'ID', 'Asia', '142', 'South-Eastern Asia', '035', TRUE),\n",
	"('', 'Iran (Islamic Republic of)', 'IR', 'Asia', '142', 'Southern Asia', '034', TRUE),\n",
	"('', 'Iraq', 'IQ', 'Asia', '142', 'Western Asia', '145', TRUE),\n",
	"('', 'Ireland', 'IE', 'Europe', '150', 'Northern Europe', '154', TRUE),\n",
	"('', 'Isle of Man', 'IM', 'Europe', '150', 'Northern Europe', '154', TRUE),\n",
	"('', 'Israel', 'IL', 'Asia', '142', 'Western Asia', '145', TRUE),\n",
	"('', 'Italy', 'IT', 'Europe', '150', 'Southern Europe', '039', TRUE),\n",
	"('', 'Jamaica', 'JM', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Japan', 'JP', 'Asia', '142', 'Eastern Asia', '030', TRUE),\n",
	"('', 'Jersey', 'JE', 'Europe', '150', 'Northern Europe', '154', TRUE),\n",
	"('', 'Jordan', 'JO', 'Asia', '142', 'Western Asia', '145', TRUE),\n",
	"('', 'Kazakhstan', 'KZ', 'Asia', '142', 'Central Asia', '143', TRUE),\n",
	"('', 'Kenya', 'KE', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'Kiribati', 'KI', 'Oceania', '009', 'Micronesia', '057', TRUE),\n",
	"('', 'Korea (Democratic People\'s Republic of)', 'KP', 'Asia', '142', 'Eastern Asia', '030', TRUE),\n",
	"('', 'Korea (Republic of)', 'KR', 'Asia', '142', 'Eastern Asia', '030', TRUE),\n",
	"('', 'Kuwait', 'KW', 'Asia', '142', 'Western Asia', '145', TRUE),\n",
	"('', 'Kyrgyzstan', 'KG', 'Asia', '142', 'Central Asia', '143', TRUE),\n",
	"('', 'Lao People\'s Democratic Republic', 'LA', 'Asia', '142', 'South-Eastern Asia', '035', TRUE),\n",
	"('', 'Latvia', 'LV', 'Europe', '150', 'Northern Europe', '154', TRUE),\n",
	"('', 'Lebanon', 'LB', 'Asia', '142', 'Western Asia', '145', TRUE),\n",
	"('', 'Lesotho', 'LS', 'Africa', '002', 'Southern Africa', '018', TRUE),\n",
	"('', 'Liberia', 'LR', 'Africa', '002', 'Western Africa', '011', TRUE),\n",
	"('', 'Libya', 'LY', 'Africa', '002', 'Northern Africa', '015', TRUE),\n",
	"('', 'Liechtenstein', 'LI', 'Europe', '150', 'Western Europe', '155', TRUE),\n",
	"('', 'Lithuania', 'LT', 'Europe', '150', 'Northern Europe', '154', TRUE),\n",
	"('', 'Luxembourg', 'LU', 'Europe', '150', 'Western Europe', '155', TRUE),\n",
	"('', 'Macao', 'MO', 'Asia', '142', 'Eastern Asia', '030', TRUE),\n",
	"('', 'Macedonia (the former Yugoslav Republic of)', 'MK', 'Europe', '150', 'Southern Europe', '039', TRUE),\n",
	"('', 'Madagascar', 'MG', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'Malawi', 'MW', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'Malaysia', 'MY', 'Asia', '142', 'South-Eastern Asia', '035', TRUE),\n",
	"('', 'Maldives', 'MV', 'Asia', '142', 'Southern Asia', '034', TRUE),\n",
	"('', 'Mali', 'ML', 'Africa', '002', 'Western Africa', '011', TRUE),\n",
	"('', 'Malta', 'MT', 'Europe', '150', 'Southern Europe', '039', TRUE),\n",
	"('', 'Marshall Islands', 'MH', 'Oceania', '009', 'Micronesia', '057', TRUE),\n",
	"('', 'Martinique', 'MQ', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Mauritania', 'MR', 'Africa', '002', 'Western Africa', '011', TRUE),\n",
	"('', 'Mauritius', 'MU', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'Mayotte', 'YT', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'Mexico', 'MX', 'Americas', '019', 'Central America', '013', TRUE),\n",
	"('', 'Micronesia (Federated States of)', 'FM', 'Oceania', '009', 'Micronesia', '057', TRUE),\n",
	"('', 'Moldova (Republic of)', 'MD', 'Europe', '150', 'Eastern Europe', '151', TRUE),\n",
	"('', 'Monaco', 'MC', 'Europe', '150', 'Western Europe', '155', TRUE),\n",
	"('', 'Mongolia', 'MN', 'Asia', '142', 'Eastern Asia', '030', TRUE),\n",
	"('', 'Montenegro', 'ME', 'Europe', '150', 'Southern Europe', '039', TRUE),\n",
	"('', 'Montserrat', 'MS', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Morocco', 'MA', 'Africa', '002', 'Northern Africa', '015', TRUE),\n",
	"('', 'Mozambique', 'MZ', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'Myanmar', 'MM', 'Asia', '142', 'South-Eastern Asia', '035', TRUE),\n",
	"('', 'Namibia', 'NA', 'Africa', '002', 'Southern Africa', '018', TRUE),\n",
	"('', 'Nauru', 'NR', 'Oceania', '009', 'Micronesia', '057', TRUE),\n",
	"('', 'Nepal', 'NP', 'Asia', '142', 'Southern Asia', '034', TRUE),\n",
	"('', 'Netherlands', 'NL', 'Europe', '150', 'Western Europe', '155', TRUE),\n",
	"('', 'New Caledonia', 'NC', 'Oceania', '009', 'Melanesia', '054', TRUE),\n",
	"('', 'New Zealand', 'NZ', 'Oceania', '009', 'Australia and New Zealand', '053', TRUE),\n",
	"('', 'Nicaragua', 'NI', 'Americas', '019', 'Central America', '013', TRUE),\n",
	"('', 'Niger', 'NE', 'Africa', '002', 'Western Africa', '011', TRUE),\n",
	"('', 'Nigeria', 'NG', 'Africa', '002', 'Western Africa', '011', TRUE),\n",
	"('', 'Niue', 'NU', 'Oceania', '009', 'Polynesia', '061', TRUE),\n",
	"('', 'Norfolk Island', 'NF', 'Oceania', '009', 'Australia and New Zealand', '053', TRUE),\n",
	"('', 'Northern Mariana Islands', 'MP', 'Oceania', '009', 'Micronesia', '057', TRUE),\n",
	"('', 'Norway', 'NO', 'Europe', '150', 'Northern Europe', '154', FALSE),\n",
	"('', 'Oman', 'OM', 'Asia', '142', 'Western Asia', '145', TRUE),\n",
	"('', 'Pakistan', 'PK', 'Asia', '142', 'Southern Asia', '034', TRUE),\n",
	"('', 'Palau', 'PW', 'Oceania', '009', 'Micronesia', '057', TRUE),\n",
	"('', 'Palestine, State of', 'PS', 'Asia', '142', 'Western Asia', '145', TRUE),\n",
	"('', 'Panama', 'PA', 'Americas', '019', 'Central America', '013', TRUE),\n",
	"('', 'Papua New Guinea', 'PG', 'Oceania', '009', 'Melanesia', '054', TRUE),\n",
	"('', 'Paraguay', 'PY', 'Americas', '019', 'South America', '005', TRUE),\n",
	"('', 'Peru', 'PE', 'Americas', '019', 'South America', '005', TRUE),\n",
	"('', 'Philippines', 'PH', 'Asia', '142', 'South-Eastern Asia', '035', TRUE),\n",
	"('', 'Pitcairn', 'PN', 'Oceania', '009', 'Polynesia', '061', TRUE),\n",
	"('', 'Poland', 'PL', 'Europe', '150', 'Eastern Europe', '151', TRUE),\n",
	"('', 'Portugal', 'PT', 'Europe', '150', 'Southern Europe', '039', TRUE),\n",
	"('', 'Puerto Rico', 'PR', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Qatar', 'QA', 'Asia', '142', 'Western Asia', '145', TRUE),\n",
	"('', 'Réunion', 'RE', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'Romania', 'RO', 'Europe', '150', 'Eastern Europe', '151', TRUE),\n",
	"('', 'Russian Federation', 'RU', 'Europe', '150', 'Eastern Europe', '151', TRUE),\n",
	"('', 'Rwanda', 'RW', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'Saint Barthélemy', 'BL', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Saint Helena, Ascension and Tristan da Cunha', 'SH', 'Africa', '002', 'Western Africa', '011', TRUE),\n",
	"('', 'Saint Kitts and Nevis', 'KN', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Saint Lucia', 'LC', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Saint Martin (French part)', 'MF', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Saint Pierre and Miquelon', 'PM', 'Americas', '019', 'Northern America', '021', TRUE),\n",
	"('', 'Saint Vincent and the Grenadines', 'VC', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Samoa', 'WS', 'Oceania', '009', 'Polynesia', '061', TRUE),\n",
	"('', 'San Marino', 'SM', 'Europe', '150', 'Southern Europe', '039', TRUE),\n",
	"('', 'Sao Tome and Principe', 'ST', 'Africa', '002', 'Middle Africa', '017', TRUE),\n",
	"('', 'Saudi Arabia', 'SA', 'Asia', '142', 'Western Asia', '145', TRUE),\n",
	"('', 'Senegal', 'SN', 'Africa', '002', 'Western Africa', '011', TRUE),\n",
	"('', 'Serbia', 'RS', 'Europe', '150', 'Southern Europe', '039', TRUE),\n",
	"('', 'Seychelles', 'SC', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'Sierra Leone', 'SL', 'Africa', '002', 'Western Africa', '011', TRUE),\n",
	"('', 'Singapore', 'SG', 'Asia', '142', 'South-Eastern Asia', '035', TRUE),\n",
	"('', 'Sint Maarten (Dutch part)', 'SX', 'Americas', '019', 'Caribbean', '029', FALSE),\n",
	"('', 'Slovakia', 'SK', 'Europe', '150', 'Eastern Europe', '151', TRUE),\n",
	"('', 'Slovenia', 'SI', 'Europe', '150', 'Southern Europe', '039', TRUE),\n",
	"('', 'Solomon Islands', 'SB', 'Oceania', '009', 'Melanesia', '054', TRUE),\n",
	"('', 'Somalia', 'SO', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'South Africa', 'ZA', 'Africa', '002', 'Southern Africa', '018', TRUE),\n",
	"('', 'South Georgia and the South Sandwich Islands', 'GS', '', '', '', '', FALSE),\n",
	"('', 'South Sudan', 'SS', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'Spain', 'ES', 'Europe', '150', 'Southern Europe', '039', TRUE),\n",
	"('', 'Sri Lanka', 'LK', 'Asia', '142', 'Southern Asia', '034', TRUE),\n",
	"('', 'Sudan', 'SD', 'Africa', '002', 'Northern Africa', '015', TRUE),\n",
	"('', 'Suriname', 'SR', 'Americas', '019', 'South America', '005', TRUE),\n",
	"('', 'Svalbard and Jan Mayen', 'SJ', 'Europe', '150', 'Northern Europe', '154', TRUE),\n",
	"('', 'Swaziland', 'SZ', 'Africa', '002', 'Southern Africa', '018', TRUE),\n",
	"('', 'Sweden', 'SE', 'Europe', '150', 'Northern Europe', '154', TRUE),\n",
	"('', 'Switzerland', 'CH', 'Europe', '150', 'Western Europe', '155', TRUE),\n",
	"('', 'Syrian Arab Republic', 'SY', 'Asia', '142', 'Western Asia', '145', TRUE),\n",
	"('', 'Taiwan, Province of China', 'TW', 'Asia', '142', 'Eastern Asia', '030', TRUE),\n",
	"('', 'Tajikistan', 'TJ', 'Asia', '142', 'Central Asia', '143', TRUE),\n",
	"('', 'Tanzania, United Republic of', 'TZ', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'Thailand', 'TH', 'Asia', '142', 'South-Eastern Asia', '035', TRUE),\n",
	"('', 'Timor-Leste', 'TL', 'Asia', '142', 'South-Eastern Asia', '035', TRUE),\n",
	"('', 'Togo', 'TG', 'Africa', '002', 'Western Africa', '011', TRUE),\n",
	"('', 'Tokelau', 'TK', 'Oceania', '009', 'Polynesia', '061', TRUE),\n",
	"('', 'Tonga', 'TO', 'Oceania', '009', 'Polynesia', '061', TRUE),\n",
	"('', 'Trinidad and Tobago', 'TT', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Tunisia', 'TN', 'Africa', '002', 'Northern Africa', '015', TRUE),\n",
	"('', 'Turkey', 'TR', 'Asia', '142', 'Western Asia', '145', TRUE),\n",
	"('', 'Turkmenistan', 'TM', 'Asia', '142', 'Central Asia', '143', TRUE),\n",
	"('', 'Turks and Caicos Islands', 'TC', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Tuvalu', 'TV', 'Oceania', '009', 'Polynesia', '061', TRUE),\n",
	"('', 'Uganda', 'UG', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'Ukraine', 'UA', 'Europe', '150', 'Eastern Europe', '151', TRUE),\n",
	"('', 'United Arab Emirates', 'AE', 'Asia', '142', 'Western Asia', '145', TRUE),\n",
	"('', 'United Kingdom of Great Britain and Northern Ireland', 'GB', 'Europe', '150', 'Northern Europe', '154', TRUE),\n",
	"('', 'United States of America', 'US', 'Americas', '019', 'Northern America', '021', TRUE),\n",
	"('', 'United States Minor Outlying Islands', 'UM', '', '', '', '', FALSE),\n",
	"('', 'Uruguay', 'UY', 'Americas', '019', 'South America', '005', TRUE),\n",
	"('', 'Uzbekistan', 'UZ', 'Asia', '142', 'Central Asia', '143', TRUE),\n",
	"('', 'Vanuatu', 'VU', 'Oceania', '009', 'Melanesia', '054', TRUE),\n",
	"('', 'Venezuela (Bolivarian Republic of)', 'VE', 'Americas', '019', 'South America', '005', TRUE),\n",
	"('', 'Viet Nam', 'VN', 'Asia', '142', 'South-Eastern Asia', '035', TRUE),\n",
	"('', 'Virgin Islands (British)', 'VG', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Virgin Islands (U.S.)', 'VI', 'Americas', '019', 'Caribbean', '029', TRUE),\n",
	"('', 'Wallis and Futuna', 'WF', 'Oceania', '009', 'Polynesia', '061', TRUE),\n",
	"('', 'Western Sahara', 'EH', 'Africa', '002', 'Northern Africa', '015', TRUE),\n",
	"('', 'Yemen', 'YE', 'Asia', '142', 'Western Asia', '145', TRUE),\n",
	"('', 'Zambia', 'ZM', 'Africa', '002', 'Eastern Africa', '014', TRUE),\n",
	"('', 'Zimbabwe', 'ZW', 'Africa', '002', 'Eastern Africa', '014', TRUE)",
);
