<?php
/**
 * Static list of ISO 3166 region names and codes that will
 * be stored in database on activation
 *
 * @link       https://github.com/garretthunter
 * @since      1.1.0
 *
 * @package    Thematic_Maps
 * @subpackage Thematic_Maps/includes
 */

$iso_regions = array (
	"('', 'Afghanistan', 'AF', 'Country'),\n",
	"('', 'Africa', '002', 'Continent'),\n",
	"('', 'Åland Islands', 'AX', 'Country'),\n",
	"('', 'Albania', 'AL', 'Country'),\n",
	"('', 'Algeria', 'DZ', 'Country'),\n",
	"('', 'American Samoa', 'AS', 'Country'),\n",
	"('', 'Americas', '019', 'Continent'),\n",
	"('', 'Andorra', 'AD', 'Country'),\n",
	"('', 'Angola', 'AO', 'Country'),\n",
	"('', 'Anguilla', 'AI', 'Country'),\n",
	"('', 'Antigua and Barbuda', 'AG', 'Country'),\n",
	"('', 'Argentina', 'AR', 'Country'),\n",
	"('', 'Armenia', 'AM', 'Country'),\n",
	"('', 'Aruba', 'AW', 'Country'),\n",
	"('', 'Asia', '142', 'Continent'),\n",
	"('', 'Australia', 'AU', 'Country'),\n",
	"('', 'Australia and New Zealand', '053', 'Sub-continent'),\n",
	"('', 'Austria', 'AT', 'Country'),\n",
	"('', 'Azerbaijan', 'AZ', 'Country'),\n",
	"('', 'Bahamas', 'BS', 'Country'),\n",
	"('', 'Bahrain', 'BH', 'Country'),\n",
	"('', 'Bangladesh', 'BD', 'Country'),\n",
	"('', 'Barbados', 'BB', 'Country'),\n",
	"('', 'Belarus', 'BY', 'Country'),\n",
	"('', 'Belgium', 'BE', 'Country'),\n",
	"('', 'Belize', 'BZ', 'Country'),\n",
	"('', 'Benin', 'BJ', 'Country'),\n",
	"('', 'Bermuda', 'BM', 'Country'),\n",
	"('', 'Bhutan', 'BT', 'Country'),\n",
	"('', 'Bolivia (Plurinational State of)', 'BO', 'Country'),\n",
	"('', 'Bonaire, Sint Eustatius and Saba', 'BQ', 'Country'),\n",
	"('', 'Bosnia and Herzegovina', 'BA', 'Country'),\n",
	"('', 'Botswana', 'BW', 'Country'),\n",
	"('', 'Brazil', 'BR', 'Country'),\n",
	"('', 'Brunei Darussalam', 'BN', 'Country'),\n",
	"('', 'Bulgaria', 'BG', 'Country'),\n",
	"('', 'Burkina Faso', 'BF', 'Country'),\n",
	"('', 'Burundi', 'BI', 'Country'),\n",
	"('', 'Cabo Verde', 'CV', 'Country'),\n",
	"('', 'Cambodia', 'KH', 'Country'),\n",
	"('', 'Cameroon', 'CM', 'Country'),\n",
	"('', 'Canada', 'CA', 'Country'),\n",
	"('', 'Caribbean', '029', 'Sub-continent'),\n",
	"('', 'Cayman Islands', 'KY', 'Country'),\n",
	"('', 'Central African Republic', 'CF', 'Country'),\n",
	"('', 'Central America', '013', 'Sub-continent'),\n",
	"('', 'Central Asia', '143', 'Sub-continent'),\n",
	"('', 'Chad', 'TD', 'Country'),\n",
	"('', 'Chile', 'CL', 'Country'),\n",
	"('', 'China', 'CN', 'Country'),\n",
	"('', 'Colombia', 'CO', 'Country'),\n",
	"('', 'Comoros', 'KM', 'Country'),\n",
	"('', 'Congo', 'CG', 'Country'),\n",
	"('', 'Congo (Democratic Republic of the)', 'CD', 'Country'),\n",
	"('', 'Cook Islands', 'CK', 'Country'),\n",
	"('', 'Costa Rica', 'CR', 'Country'),\n",
	"('', 'Côte d\'Ivoire', 'CI', 'Country'),\n",
	"('', 'Croatia', 'HR', 'Country'),\n",
	"('', 'Cuba', 'CU', 'Country'),\n",
	"('', 'Curaçao', 'CW', 'Country'),\n",
	"('', 'Cyprus', 'CY', 'Country'),\n",
	"('', 'Czech Republic', 'CZ', 'Country'),\n",
	"('', 'Denmark', 'DK', 'Country'),\n",
	"('', 'Djibouti', 'DJ', 'Country'),\n",
	"('', 'Dominica', 'DM', 'Country'),\n",
	"('', 'Dominican Republic', 'DO', 'Country'),\n",
	"('', 'Eastern Africa', '014', 'Sub-continent'),\n",
	"('', 'Eastern Asia', '030', 'Sub-continent'),\n",
	"('', 'Eastern Europe', '151', 'Sub-continent'),\n",
	"('', 'Ecuador', 'EC', 'Country'),\n",
	"('', 'Egypt', 'EG', 'Country'),\n",
	"('', 'El Salvador', 'SV', 'Country'),\n",
	"('', 'Equatorial Guinea', 'GQ', 'Country'),\n",
	"('', 'Eritrea', 'ER', 'Country'),\n",
	"('', 'Estonia', 'EE', 'Country'),\n",
	"('', 'Ethiopia', 'ET', 'Country'),\n",
	"('', 'Europe', '150', 'Continent'),\n",
	"('', 'Falkland Islands (Malvinas)', 'FK', 'Country'),\n",
	"('', 'Faroe Islands', 'FO', 'Country'),\n",
	"('', 'Fiji', 'FJ', 'Country'),\n",
	"('', 'Finland', 'FI', 'Country'),\n",
	"('', 'France', 'FR', 'Country'),\n",
	"('', 'French Guiana', 'GF', 'Country'),\n",
	"('', 'French Polynesia', 'PF', 'Country'),\n",
	"('', 'Gabon', 'GA', 'Country'),\n",
	"('', 'Gambia', 'GM', 'Country'),\n",
	"('', 'Georgia', 'GE', 'Country'),\n",
	"('', 'Germany', 'DE', 'Country'),\n",
	"('', 'Ghana', 'GH', 'Country'),\n",
	"('', 'Gibraltar', 'GI', 'Country'),\n",
	"('', 'Greece', 'GR', 'Country'),\n",
	"('', 'Greenland', 'GL', 'Country'),\n",
	"('', 'Grenada', 'GD', 'Country'),\n",
	"('', 'Guadeloupe', 'GP', 'Country'),\n",
	"('', 'Guam', 'GU', 'Country'),\n",
	"('', 'Guatemala', 'GT', 'Country'),\n",
	"('', 'Guernsey', 'GG', 'Country'),\n",
	"('', 'Guinea', 'GN', 'Country'),\n",
	"('', 'Guinea-Bissau', 'GW', 'Country'),\n",
	"('', 'Guyana', 'GY', 'Country'),\n",
	"('', 'Haiti', 'HT', 'Country'),\n",
	"('', 'Holy See', 'VA', 'Country'),\n",
	"('', 'Honduras', 'HN', 'Country'),\n",
	"('', 'Hong Kong', 'HK', 'Country'),\n",
	"('', 'Hungary', 'HU', 'Country'),\n",
	"('', 'Iceland', 'IS', 'Country'),\n",
	"('', 'India', 'IN', 'Country'),\n",
	"('', 'Indonesia', 'ID', 'Country'),\n",
	"('', 'Iran (Islamic Republic of)', 'IR', 'Country'),\n",
	"('', 'Iraq', 'IQ', 'Country'),\n",
	"('', 'Ireland', 'IE', 'Country'),\n",
	"('', 'Isle of Man', 'IM', 'Country'),\n",
	"('', 'Israel', 'IL', 'Country'),\n",
	"('', 'Italy', 'IT', 'Country'),\n",
	"('', 'Jamaica', 'JM', 'Country'),\n",
	"('', 'Japan', 'JP', 'Country'),\n",
	"('', 'Jersey', 'JE', 'Country'),\n",
	"('', 'Jordan', 'JO', 'Country'),\n",
	"('', 'Kazakhstan', 'KZ', 'Country'),\n",
	"('', 'Kenya', 'KE', 'Country'),\n",
	"('', 'Kiribati', 'KI', 'Country'),\n",
	"('', 'Korea (Democratic People\'s Republic of)', 'KP', 'Country'),\n",
	"('', 'Korea (Republic of)', 'KR', 'Country'),\n",
	"('', 'Kuwait', 'KW', 'Country'),\n",
	"('', 'Kyrgyzstan', 'KG', 'Country'),\n",
	"('', 'Lao People\'s Democratic Republic', 'LA', 'Country'),\n",
	"('', 'Latvia', 'LV', 'Country'),\n",
	"('', 'Lebanon', 'LB', 'Country'),\n",
	"('', 'Lesotho', 'LS', 'Country'),\n",
	"('', 'Liberia', 'LR', 'Country'),\n",
	"('', 'Libya', 'LY', 'Country'),\n",
	"('', 'Liechtenstein', 'LI', 'Country'),\n",
	"('', 'Lithuania', 'LT', 'Country'),\n",
	"('', 'Luxembourg', 'LU', 'Country'),\n",
	"('', 'Macao', 'MO', 'Country'),\n",
	"('', 'Macedonia (the former Yugoslav Republic of)', 'MK', 'Country'),\n",
	"('', 'Madagascar', 'MG', 'Country'),\n",
	"('', 'Malawi', 'MW', 'Country'),\n",
	"('', 'Malaysia', 'MY', 'Country'),\n",
	"('', 'Maldives', 'MV', 'Country'),\n",
	"('', 'Mali', 'ML', 'Country'),\n",
	"('', 'Malta', 'MT', 'Country'),\n",
	"('', 'Marshall Islands', 'MH', 'Country'),\n",
	"('', 'Martinique', 'MQ', 'Country'),\n",
	"('', 'Mauritania', 'MR', 'Country'),\n",
	"('', 'Mauritius', 'MU', 'Country'),\n",
	"('', 'Mayotte', 'YT', 'Country'),\n",
	"('', 'Melanesia', '054', 'Sub-continent'),\n",
	"('', 'Mexico', 'MX', 'Country'),\n",
	"('', 'Micronesia', '057', 'Sub-continent'),\n",
	"('', 'Micronesia (Federated States of)', 'FM', 'Country'),\n",
	"('', 'Middle Africa', '017', 'Sub-continent'),\n",
	"('', 'Moldova (Republic of)', 'MD', 'Country'),\n",
	"('', 'Monaco', 'MC', 'Country'),\n",
	"('', 'Mongolia', 'MN', 'Country'),\n",
	"('', 'Montenegro', 'ME', 'Country'),\n",
	"('', 'Montserrat', 'MS', 'Country'),\n",
	"('', 'Morocco', 'MA', 'Country'),\n",
	"('', 'Mozambique', 'MZ', 'Country'),\n",
	"('', 'Myanmar', 'MM', 'Country'),\n",
	"('', 'Namibia', 'NA', 'Country'),\n",
	"('', 'Nauru', 'NR', 'Country'),\n",
	"('', 'Nepal', 'NP', 'Country'),\n",
	"('', 'Netherlands', 'NL', 'Country'),\n",
	"('', 'New Caledonia', 'NC', 'Country'),\n",
	"('', 'New Zealand', 'NZ', 'Country'),\n",
	"('', 'Nicaragua', 'NI', 'Country'),\n",
	"('', 'Niger', 'NE', 'Country'),\n",
	"('', 'Nigeria', 'NG', 'Country'),\n",
	"('', 'Niue', 'NU', 'Country'),\n",
	"('', 'Norfolk Island', 'NF', 'Country'),\n",
	"('', 'Northern Africa', '015', 'Sub-continent'),\n",
	"('', 'Northern America', '021', 'Sub-continent'),\n",
	"('', 'Northern Europe', '154', 'Sub-continent'),\n",
	"('', 'Northern Mariana Islands', 'MP', 'Country'),\n",
	"('', 'Norway', 'NO', 'Country'),\n",
	"('', 'Oceania', '009', 'Continent'),\n",
	"('', 'Oman', 'OM', 'Country'),\n",
	"('', 'Pakistan', 'PK', 'Country'),\n",
	"('', 'Palau', 'PW', 'Country'),\n",
	"('', 'Palestine, State of', 'PS', 'Country'),\n",
	"('', 'Panama', 'PA', 'Country'),\n",
	"('', 'Papua New Guinea', 'PG', 'Country'),\n",
	"('', 'Paraguay', 'PY', 'Country'),\n",
	"('', 'Peru', 'PE', 'Country'),\n",
	"('', 'Philippines', 'PH', 'Country'),\n",
	"('', 'Pitcairn', 'PN', 'Country'),\n",
	"('', 'Poland', 'PL', 'Country'),\n",
	"('', 'Polynesia', '061', 'Sub-continent'),\n",
	"('', 'Portugal', 'PT', 'Country'),\n",
	"('', 'Puerto Rico', 'PR', 'Country'),\n",
	"('', 'Qatar', 'QA', 'Country'),\n",
	"('', 'Réunion', 'RE', 'Country'),\n",
	"('', 'Romania', 'RO', 'Country'),\n",
	"('', 'Russian Federation', 'RU', 'Country'),\n",
	"('', 'Rwanda', 'RW', 'Country'),\n",
	"('', 'Saint Barthélemy', 'BL', 'Country'),\n",
	"('', 'Saint Helena, Ascension and Tristan da Cunha', 'SH', 'Country'),\n",
	"('', 'Saint Kitts and Nevis', 'KN', 'Country'),\n",
	"('', 'Saint Lucia', 'LC', 'Country'),\n",
	"('', 'Saint Martin (French part)', 'MF', 'Country'),\n",
	"('', 'Saint Pierre and Miquelon', 'PM', 'Country'),\n",
	"('', 'Saint Vincent and the Grenadines', 'VC', 'Country'),\n",
	"('', 'Samoa', 'WS', 'Country'),\n",
	"('', 'San Marino', 'SM', 'Country'),\n",
	"('', 'Sao Tome and Principe', 'ST', 'Country'),\n",
	"('', 'Saudi Arabia', 'SA', 'Country'),\n",
	"('', 'Senegal', 'SN', 'Country'),\n",
	"('', 'Serbia', 'RS', 'Country'),\n",
	"('', 'Seychelles', 'SC', 'Country'),\n",
	"('', 'Sierra Leone', 'SL', 'Country'),\n",
	"('', 'Singapore', 'SG', 'Country'),\n",
	"('', 'Sint Maarten (Dutch part)', 'SX', 'Country'),\n",
	"('', 'Slovakia', 'SK', 'Country'),\n",
	"('', 'Slovenia', 'SI', 'Country'),\n",
	"('', 'Solomon Islands', 'SB', 'Country'),\n",
	"('', 'Somalia', 'SO', 'Country'),\n",
	"('', 'South Africa', 'ZA', 'Country'),\n",
	"('', 'South America', '005', 'Sub-continent'),\n",
	"('', 'South Sudan', 'SS', 'Country'),\n",
	"('', 'South-Eastern Asia', '035', 'Sub-continent'),\n",
	"('', 'Southern Africa', '018', 'Sub-continent'),\n",
	"('', 'Southern Asia', '034', 'Sub-continent'),\n",
	"('', 'Southern Europe', '039', 'Sub-continent'),\n",
	"('', 'Spain', 'ES', 'Country'),\n",
	"('', 'Sri Lanka', 'LK', 'Country'),\n",
	"('', 'Sudan', 'SD', 'Country'),\n",
	"('', 'Suriname', 'SR', 'Country'),\n",
	"('', 'Svalbard and Jan Mayen', 'SJ', 'Country'),\n",
	"('', 'Swaziland', 'SZ', 'Country'),\n",
	"('', 'Sweden', 'SE', 'Country'),\n",
	"('', 'Switzerland', 'CH', 'Country'),\n",
	"('', 'Syrian Arab Republic', 'SY', 'Country'),\n",
	"('', 'Taiwan, Province of China', 'TW', 'Country'),\n",
	"('', 'Tajikistan', 'TJ', 'Country'),\n",
	"('', 'Tanzania, United Republic of', 'TZ', 'Country'),\n",
	"('', 'Thailand', 'TH', 'Country'),\n",
	"('', 'Timor-Leste', 'TL', 'Country'),\n",
	"('', 'Togo', 'TG', 'Country'),\n",
	"('', 'Tokelau', 'TK', 'Country'),\n",
	"('', 'Tonga', 'TO', 'Country'),\n",
	"('', 'Trinidad and Tobago', 'TT', 'Country'),\n",
	"('', 'Tunisia', 'TN', 'Country'),\n",
	"('', 'Turkey', 'TR', 'Country'),\n",
	"('', 'Turkmenistan', 'TM', 'Country'),\n",
	"('', 'Turks and Caicos Islands', 'TC', 'Country'),\n",
	"('', 'Tuvalu', 'TV', 'Country'),\n",
	"('', 'Uganda', 'UG', 'Country'),\n",
	"('', 'Ukraine', 'UA', 'Country'),\n",
	"('', 'United Arab Emirates', 'AE', 'Country'),\n",
	"('', 'United Kingdom of Great Britain and Northern Ireland', 'GB', 'Country'),\n",
	"('', 'United States of America', 'US', 'Country'),\n",
	"('', 'Uruguay', 'UY', 'Country'),\n",
	"('', 'Uzbekistan', 'UZ', 'Country'),\n",
	"('', 'Vanuatu', 'VU', 'Country'),\n",
	"('', 'Venezuela (Bolivarian Republic of)', 'VE', 'Country'),\n",
	"('', 'Viet Nam', 'VN', 'Country'),\n",
	"('', 'Virgin Islands (British)', 'VG', 'Country'),\n",
	"('', 'Virgin Islands (U.S.)', 'VI', 'Country'),\n",
	"('', 'Wallis and Futuna', 'WF', 'Country'),\n",
	"('', 'Western Africa', '011', 'Sub-continent'),\n",
	"('', 'Western Asia', '145', 'Sub-continent'),\n",
	"('', 'Western Europe', '155', 'Sub-continent'),\n",
	"('', 'Western Sahara', 'EH', 'Country'),\n",
	"('', 'Yemen', 'YE', 'Country'),\n",
	"('', 'Zambia', 'ZM', 'Country'),\n",
	"('', 'Zimbabwe', 'ZW', 'Country'),\n",
);
